[defaults]
duration_mins = 60
open_browser = true
calendar_id = "primary"

[flags]
day = ["-day", "--day"]
location = ["-l", "--location"]
description = ["-des", "--description"]
timezone = ["-tz", "--timezone"]
notification = ["-notif", "--notification"]
dry_run = ["-dr", "--dry-run"]

[timezones]
ET = "America/New_York"
CT = "America/Chicago"
MT = "America/Denver"
PT = "America/Los_Angeles"
UTC = "UTC"
GMT = "UTC"
